### ISSUE TITLE
Changes in spatialreg and splm impact strm

### ISSUE THREAD

**Issue by rsbivand** [mkamenet3/strm#34]
Because **spatialreg** is diverging from **spdep**, and because model-fitting functions in **spdep** will soon be defunct, the names of model output classes have been changed, and many S3 methods are no longer exported from the **spatialreg** `NAMESPACE`. Please install: `remotes::install_github("r-spatial/spatialreg")` and try to install **splm** from R-Forge (revision 227); I get the following check log with these: 
[00check.log](https://github.com/mkamenet3/strm/files/6147771/00check.log). 
You will need to work around the lag in **broom** not yet having a tidy method for the renamed `sarlm` class from **spdep**, now `Sarlm` in **spatialreg**. The coefficient table will be re-arranged anyway, so the spdep/sarlm tidy method will not work for the spatialreg version. Splitting out modelling functions was intended to make it easier to develop these faster, leaving **spdep** with neighbour object creation and tests for spatial autocorrelation.

**Comment by mkamenet3** [comment]
Hello and thank you for letting me know. I got around the **broom** dependency with **gt** and updated the requirements. The vignettes in the GitHub version should work now. Looking forward to continue exploring the new **spatialreg**.

**Comment by rsbivand** [comment]
The 1.1-8 version of **spatialreg** will be on CRAN shortly, so you will need to submit your fixed package soon. Thanks for being pro-active and handling this straight away.

**Comment by mkamenet3** [comment]
Thank you for letting me know - I'll submit the fix to CRAN shortly.
